### PR TITLE
Update valhalla image to use Ubuntu 16.04, and add pelias cli for valhalla.

### PR DESCRIPTION
**Pull request by JWileczek**
This updates the valhalla image used in the docker setup, and creates a command to use it as an alternative to the normal polyline creation metod.

Some notes on this update as it was incredibly frustrating to get working:
Moved away from `pelias/baseimage` as the base docker image for valhalla. There are a couple reasons for this. The install instructions originally used in the image that relied on the PPA recipe don't work for Ubuntu latest (18.04). After finding this out, I attempted to build the project from source using the `pelias/baseimage` and was able to get it successfully building + linking, but found that there was one, and only one, specific test in valhalla failing afterwards. This test failure coupled with a consistently stalled import of polyline data when running through the portland test case had me guessing this test failure was causing an issue. I tried to track down this error for quite a while thinking it was related to how libraries were being linked/loaded before ultimately coming across this closed issue in the valhalla repo actually referencing it. 
https://github.com/valhalla/valhalla/issues/1437
Unfortunately, this closed issue didn't actually fix the underlying problem but it did identify it. ( I wish this was documented anywhere else in the readme or documentation for the actual repo. One would think if there is a known test issue with a latest distribution of ubuntu it would be documented somewhere in the readme, so some developer like myself who sees a passing latest linux build with no open issues surrounding the test in question doesn't spend hours thinking some library is configured incorrectly.)
So after falling back to using the last known working ubuntu release, the recipe works again for the install, so I dropped building from source all together. I also created some commands to use valhalla as an alternative means to generating the polyline data. 
I ran through the portland test using valhalla successfully with 98% of the tests passing, but haven't run through the other projects yet. If others could test out the different projects and verify they are able to run through the projects successfully this change should be ready to pull in. It might be worthwhile to update the larger country/continent projects readme to use the valhalla method of polyline generation since it's intended for larger pbf files, but I figured we can add that to the PR quickly if that makes the most sense.

### CODE REVIEW

**Comment by orangejulius** [comment]
Nice, this is awesome. Figuring out how to cleanly support both polylines generation methods has been something we've had in the back of our minds for a while now.

I have some initial comments for this PR and then we'll probably get back to you after more testing:

### Baseimage changes
There's nothing wrong with switching away from pelias/baseimage if needed. We can also look at upgrading the baseimages to Ubuntu 18.

One important restriction we do have is that it has to be possible to run all the Pelias containers without writing to the container's root filesystem, and without running any processes as the root user. See https://github.com/pelias/docker/pull/18 for an example of how to test that behavior. If the default valhalla images run as non-root, we can use them. If not, we need to make our own. It might be as simple as extending the valhalla docker image and throwing a `USER pelias` line in a Dockerfile.

I took a look at some scripts we use to generate extracts via valhalla, and we currently use the valhalla docker images. Here's our script:

```bash
# generate valhalla config
docker run --rm -i -v "${valhalla_data_path}:/tmp/valhalla" ${valhalla_docker_image} bash <<-EOF
  valhalla_build_config \
    --mjolnir-tile-dir /tmp/valhalla/tiles \
    --mjolnir-tile-extract /tmp/valhalla/valhalla.tar \
    --mjolnir-timezone /tmp/valhalla/timezones.sqlite \
    --mjolnir-admin /tmp/valhalla/admins.sqlite > /tmp/valhalla/valhalla.json
EOF

# generate valhalla tiles
docker run --rm -i -v "${valhalla_data_path}:/tmp/valhalla" -v "${osm_pbf_local_path}:/tmp/osm.extract.pbf:ro" valhalla/docker bash <<-EOF
  # valhalla writes files to the CWD
  # https://github.com/valhalla/docker/issues/42#issuecomment-411799151
  cd /tmp/valhalla/tmp
  # generate tiles
  valhalla_build_tiles -c /tmp/valhalla/valhalla.json /tmp/osm.extract.pbf
EOF

# generate polylines file
docker run --rm -i -v "${valhalla_data_path}:/tmp/valhalla" valhalla/docker bash <<-EOF
  valhalla_export_edges --config /tmp/valhalla/valhalla.json > /tmp/valhalla/${valhalla_polyline_extract_filename}
EOF
```

### Configuration
What do you think of using an environment variable as a way to control whether `missinglink/pbf` or valhalla is used. A good example of doing that is in https://github.com/pelias/docker/pull/20. We can set `missinglink/pbf` as the default, and then users who want to build larger projects can set `valhalla` manually.

**Comment by JWileczek** [comment]
The environment variable method of controlling which polyline generation library is used makes sense to me. I'll go through this later tonight and add that change, should be easy and quick enough to do. I'm unsure if these processes are running as root vs pelias user, but I'm inclined to lean toward root with the current setup. I'll confirm that later tonight as well, and update this with another comment with my findings. Hopefully it will be as simple as adding the USER: pelias similar to the other projects, but this library in general has proven difficult over the past few days in that regard so I'm going to avoid getting my hopes up there. I hadn't seen the `valhalla/docker` images originally either, but looking at it now its latest version is also using ubuntu:16.04.

The `pelias/baseimage` is already using ubuntu:18.04, from what I've seen at least, since it's built from `ubuntu:latest`. Unforunately, using Ubuntu 18.04 creates the issue in the first place with valhalla so it will probably just be better to stick to 16.04 to avoid the hassle of fighting with sqlite.

**Comment by orangejulius** [comment]
Oh, sorry, I misread then. I thought it was the opposite situation: we were using Ubuntu 16 but the bug is with 18.

I'm actually a little concerned that we are using `ubuntu:latest` in our Baseimage (now that you mention it, I recall noticing it before). It might be better to pin to a specific `ubuntu` version to avoid unexpected changes. Migrating between Ubuntu versions is usually a huge pain and breaks a lot. @missinglink what do you think?

**Comment by JWileczek** [comment]
In light of these changes and what was discussed here in this PR comment section I came up with what may be the better solution to this spread over a couple more PRs. If these were pulled in it should make this PR unnecessary because the solution will be better incorporated directly into polyline repo.

https://github.com/pelias/baseimage/pull/9
https://github.com/pelias/polylines/pull/204

There are a lot of potential variations of these changes that I mention in some of the other PRs if we decide locking down the ubuntu distribution version isn't desired. Personally, I think it would make sense to lock down the versions to avoid random errors caused by major dependency package updates that were unknown.

**Comment by missinglink** [comment]
@JWileczek I had a look at the issue and it's easily fixed with either a symlink or ENV var:

On my Ubuntu machine:
```
$ ls -lah /usr/local/lib/libspatialite.*
-rw-r--r-- 1 root root  39M Jul 23 09:40 /usr/local/lib/libspatialite.a
-rwxr-xr-x 1 root root 1.2K Jul 23 09:40 /usr/local/lib/libspatialite.la
lrwxrwxrwx 1 root root   22 Jul 23 09:40 /usr/local/lib/libspatialite.so -> libspatialite.so.7.1.1
lrwxrwxrwx 1 root root   22 Jul 23 09:40 /usr/local/lib/libspatialite.so.7 -> libspatialite.so.7.1.1
-rwxr-xr-x 1 root root  19M Jul 23 09:40 /usr/local/lib/libspatialite.so.7.1.1
```

so if they SQLite library is looking for a file called `libspatialite` then you can add a symlink in that directory to resolve the issue.

alternatively, there may be a different issue where SQLite is not able to find the directory containing the library correctly, in this case, you can tell it explicitly where to search by setting an ENV var:

```
ENV LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
```

note: that paths may vary, you'll need to check the correct location inside the image.

**Comment by missinglink** [comment]
ok, so it works fine on `18.10` without any change:

```
FROM ubuntu:18.10

RUN apt-get update -y
RUN apt-get install -y sqlite3
RUN apt-get install -y libsqlite3-mod-spatialite

RUN dpkg --listfiles libsqlite3-mod-spatialite
RUN ls -lah /usr/lib/x86_64-linux-gnu/mod_spatialite.*

RUN sqlite3 -cmd 'SELECT load_extension("mod_spatialite"); SELECT AsGeoJSON( MakePoint( 1, 1, 4236 ) );'
```

On `18.04` you'll need to add one extra line to add a symlink:

```
FROM ubuntu:18.04

RUN apt-get update -y
RUN apt-get install -y sqlite3
RUN apt-get install -y libsqlite3-mod-spatialite

RUN dpkg --listfiles libsqlite3-mod-spatialite
RUN ls -lah /usr/lib/x86_64-linux-gnu/mod_spatialite.*

RUN ln -s /usr/lib/x86_64-linux-gnu/mod_spatialite.so /usr/lib/x86_64-linux-gnu/mod_spatialite

RUN sqlite3 -cmd 'SELECT load_extension("mod_spatialite"); SELECT AsGeoJSON( MakePoint( 1, 1, 4236 ) );'
```

**Comment by missinglink** [comment]
Also `libspatialite !== mod_spatialite`, in this case you want `mod_spatialite`

**Pull request closed without merging**
