### PR TITLE
docker compose instead of docker-compose and added project denmark

### PR DESCRIPTION
**Pull request by welrachid**
added project denmark

Just added it to be able to compile and run for the country Denmark. spent some time doing it. i guess someone could benefit from this.

Used norway as a base. Tried to do it without whosonfirst (wof) but then i didnt get any result at all. Once i added it, it worked great.

Took about an hour on a virtualbox VM (ubuntu guest) with 6GB ram and 6 CPU

### CODE REVIEW

**Comment by welrachid** [comment]
I've also edited docker compose instead of docker-compose.

This is because docker now comes with docker compose as part of it. For a fresh install docker always comes with docker compose as part of it. this means that the CLI will not run properly unless the docker.sh file is updated.

**Comment by missinglink** [comment]
Heya, thanks for the contribution. I saw that `compose` was included as a subcommand of `docker` some time back, which is awesome.

Can I ask that we decouple these two code changes into separate PRs? (ie. the `project` and the change to `compose`)

I had a quick look to try and figure out which version of `docker` it's available from and couldn't find an exact number, the [install docs](https://github.com/docker/compose#where-to-get-docker-compose) seem to suggest that it's available by default on MacOS but not for linux, is that correct? 🤔

**Comment by missinglink** [comment]
I just logged into an older Linux server I have and the command isn't available, it's likely that my software is not current, but it's indicative of an issue that other users may face and a potential headache for the maintainers.

I hope we can figure out a way for it to 'just work' for everyone.

```bash
$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'

$ docker --version
Docker version 20.10.12, build e91ed57

$ docker compose
docker: 'compose' is not a docker command.

$ uname -a
Linux *** 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by w0pr** [comment]
> I just logged into an older Linux server I have and the command isn't available, it's likely that my software is not current, but it's indicative of an issue that other users may face and a potential headache for the maintainers.

It is in docker-compose-plugin:
https://pkgs.org/download/docker-compose-plugin

**Comment by welrachid** [comment]
i've creeated: https://github.com/pelias/docker/pull/302 and https://github.com/pelias/docker/pull/303

**Pull request closed without merging**
