### PR TITLE
Add submodule documentation to Planet project

### PR DESCRIPTION
**Pull request by orangejulius**
Fixes https://github.com/pelias/docker/issues/90

### CODE REVIEW

**Comment by jeremy-rutman** [comment]
I tried `git submodule update` but it didn't seem to help matters:

```
jeremyr@bolt88:/data_c/users/jeremy/pelias/docker/projects/planet$ pelias test run 
^C^C^C^Z^Z\^C^C^CKilled
jeremyr@bolt88:/data_c/users/jeremy/pelias/docker/projects/planet$ git submodule update
jeremyr@bolt88:/data_c/users/jeremy/pelias/docker/projects/planet$ pelias test run 
...
```
I'l read up a bit on submodule and see if there's a way to verify that anything happened as a result of that update line.

**Comment by orangejulius** [comment]
Oops, sorry, there has to be a call to `git submodule init` first, before `update` (alternatively you can clone with `git clone --recursive-submodules). I've updated the docs, let me know if that helps.

**Comment by jeremy-rutman** [comment]
after `git submodule init` , removing the acceptance-tests directory (which caused a 'dir aready exists' error) and `git submodule update`  the tests start to run .  I'll have to fiddle a bit to avoid 'EAI_AGAIN' errors that are due to my proxy config but blv. this solves the main issue.

**Comment by missinglink** [comment]
submodules? 😭

**Comment by orangejulius** [comment]
Awesome, thanks @jeremy-rutman 

Yes, @missinglink, submodules are the perfect way (well, as perfect as we can get I suppose), to allow the acceptance-tests to be the tests for the planet project.

**Pull request merged**
